version: "3"
services:
  atcoder:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    container_name: atcoder
    volumes:
      - ./:/work
    working_dir: /work
    command: bash