[tool.pysen]
version = "0.9.1"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
py_version = "py37"

[[tool.pysen.lint.mypy_targets]]
paths = ["."]