FROM python:3.11.6
LABEL maintainer "Reo Hirao <reohirao116@gmail.com>"
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y software-properties-common build-essential &&\
    apt install -y gcc

COPY ./config/requirements.txt /tmp/
RUN pip3 install --upgrade pip
RUN pip3 install -r /tmp/requirements.txt

ENV PYTHONPATH=$PYTHONPATH:/work

WORKDIR /work
