FROM python:3.11.7-slim-bookworm
LABEL maintainer "Reo Hirao <reohirao116@gmail.com>"
ENV DEBIAN_FRONTEND noninteractive

RUN apt update
RUN apt install -y software-properties-common build-essential

COPY ./config/requirements.txt /tmp/
RUN pip3 install --upgrade pip
RUN pip3 install -r /tmp/requirements.txt

ENV PYTHONPATH=$PYTHONPATH:/work

WORKDIR /work
