SELECT
    AGE_GRP.AGE_NAME as '年齢階層',
    SUM(CASE WHEN SLEEP_TIME.TIME_NAME = '5時間未満' THEN SLEEP_TIME_DTL.TARGET_POP ELSE 0 END) as '5時間未満',
    SUM(CASE WHEN SLEEP_TIME.TIME_NAME = '5時間以上6時間未満' THEN SLEEP_TIME_DTL.TARGET_POP ELSE 0 END) as '5時間以上6時間未満',
    SUM(CASE WHEN SLEEP_TIME.TIME_NAME = '6時間以上7時間未満' THEN SLEEP_TIME_DTL.TARGET_POP ELSE 0 END) as '6時間以上7時間未満',
    SUM(CASE WHEN SLEEP_TIME.TIME_NAME = '7時間以上8時間未満' THEN SLEEP_TIME_DTL.TARGET_POP ELSE 0 END) as '7時間以上8時間未満',
    SUM(CASE WHEN SLEEP_TIME.TIME_NAME = '8時間以上9時間未満' THEN SLEEP_TIME_DTL.TARGET_POP ELSE 0 END) as '8時間以上9時間未満',
    SUM(CASE WHEN SLEEP_TIME.TIME_NAME = '9時間以上' THEN SLEEP_TIME_DTL.TARGET_POP ELSE 0 END) as '9時間以上',
    SUM(CASE WHEN SLEEP_TIME.TIME_NAME = '不詳' THEN SLEEP_TIME_DTL.TARGET_POP ELSE 0 END) as '不詳'
FROM SLEEP_TIME_DTL
JOIN AGE_GRP on SLEEP_TIME_DTL.AGE_CODE = AGE_GRP.AGE_CODE
JOIN SLEEP_TIME on SLEEP_TIME_DTL.TIME_CODE = SLEEP_TIME.TIME_CODE
GROUP BY 1
ORDER BY AGE_GRP.AGE_CODE